imports:
    - { resource: 'services/command.yml' }
    - { resource: 'services/form.yml' }
    - { resource: 'services/listeners.yml' }
    - { resource: 'services/storage.yml' }

services:
    fl_gmail_doctrine.sync_wrapper:
        class: FL\GmailDoctrineBundle\Services\SyncWrapper
        arguments:
            - "@fl_gmail.sync_gmail_ids"
            - "@fl_gmail.sync_messages"
            - "@fl_gmail.oauth"
            - "@fl_gmail.directory"
            - "@doctrine.orm.entity_manager"
            - "%fl_gmail.gmail_history_class%"
            - "%fl_gmail_doctrine.sync_setting_class%"
            - "%fl_gmail.gmail_ids_class%"
    fl_gmail_doctrine.client_status_wrapper:
        class: FL\GmailDoctrineBundle\Services\GoogleClientStatusWrapper
        lazy: true
        arguments:
            - "@fl_gmail.client_status"
            - "@doctrine.orm.entity_manager"
            - "%fl_gmail_doctrine.sync_setting_class%"

