imports:
    - { resource: 'services/actions.yml' }
    - { resource: 'services/command.yml' }
    - { resource: 'services/form.yml' }
    - { resource: 'services/listeners.yml' }

services:
    app.sync_wrapper:
        class: FL\GmailDoctrineBundle\Services\SyncWrapper
        arguments:
            - "@fl_gmail.sync_manager"
            - "@fl_gmail.oauth"
            - "@fl_gmail.directory"
            - "@=service('doctrine').getRepository('FL\GmailDoctrineBundle:GmailHistory')"
            - "@=service('doctrine').getRepository('FL\GmailDoctrineBundle:SyncSetting')"