services:
    fl_gmail_doctrine.command.sync:
        class: FL\GmailDoctrineBundle\Command\SyncCommand
        arguments:
            - "@fl_gmail_doctrine.sync_wrapper"
        tags:
            -  { name: console.command }
