services:
    fl_gmail_doctrine.form.settings:
        class: FL\GmailDoctrineBundle\Form\SyncSettingType
        tags:
            - { name: form.type }
        arguments:
            - "%fl_gmail_doctrine.sync_setting_class%"
    fl_gmail_doctrine.type.from:
        class: FL\GmailDoctrineBundle\Form\Type\FromType
        tags:
            - { name: form.type }
        arguments:
            - "@fl_gmail.oauth"
            - "@fl_gmail.directory"
            - "@doctrine.orm.entity_manager"
            - "%fl_gmail_doctrine.sync_setting_class%"

