services:
    fl_gmail_doctrine.listener.persist_ids:
        class: FL\GmailDoctrineBundle\EventListener\PersistIdsListener
        arguments:
            - "@doctrine.orm.entity_manager"
            - "%fl_gmail.gmail_ids_class%"
        tags:
            - { name: kernel.event_listener, event: fl_gmail.sync.ids, method: onGmailSyncIds }

    fl_gmail_doctrine.listener.persist_history:
        class: FL\GmailDoctrineBundle\EventListener\PersistHistoryListener
        arguments:
            - "@doctrine.orm.entity_manager"
            - "%fl_gmail.gmail_history_class%"
        tags:
            - { name: kernel.event_listener, event: fl_gmail.sync.history, method: onGmailSyncHistory }

    fl_gmail_doctrine.listener.persist_messages:
        class: FL\GmailDoctrineBundle\EventListener\PersistMessagesListener
        arguments:
            - "@doctrine.orm.entity_manager"
            - "%fl_gmail.gmail_message_class%"
            - "%fl_gmail.gmail_label_class%"
        tags:
            - { name: kernel.event_listener, event: fl_gmail.sync.messages, method: onGmailSyncMessages }

    fl_gmail_doctrine.listener.clean_up_messages:
        class: FL\GmailDoctrineBundle\EventListener\CleanUpMessagesListener
        arguments:
            - "%fl_gmail.gmail_message_class%"
            - "%fl_gmail.gmail_label_class%"
            - "%fl_gmail.gmail_history_class%"
            - "%fl_gmail.gmail_ids_class%"
        tags:
            - { name: doctrine.event_listener, event: preUpdate }
            - { name: doctrine.event_listener, event: preRemove }
            - { name: doctrine.event_listener, event: postFlush }

    fl_gmail_doctrine.listener.sync_message_sent:
        class: FL\GmailDoctrineBundle\EventListener\SyncMessagesSentListener
        arguments:
            - "@fl_gmail_doctrine.sync_wrapper"
        tags:
            - { name: 'swiftmailer.fl_gmail_api_mailer.plugin'}